### ISSUE TITLE
If you allow step_across to be called multiple times you lose nothing.

### ISSUE THREAD

**Issue by GrayThomas** [jackhall/Lyapunov#1]
I present a slight modification of step_across which allows it to be called multiple times without throwing an error, so long as the second (and subsequent) times a state is provided. The original restriction had prevented me from using one call to fetch the state on the far side of the boundary and another call to reset the state after a computation on the far side had been performed. This is especially important with systems which exhibit chatter, since the condition for escape from the chatter surface needs to have been surpassed before it is possible to leave the surface under the appropriate dynamics.

``` c++
void step_across(boost::python::object new_state = boost::python::object()) { 
            namespace bp = boost::python;
            if(new_state.is_none() && saved_information != BOUNDARY) RuntimeError("No boundary to step across.");
            bp::object state_tup;
            if(new_state.is_none()) state_tup = bp::make_tuple(saved_time, saved_state);
            else state_tup = bp::make_tuple(saved_time, new_state);
            system.attr("state") = state_tup;
            reset_with_events(); 
        }
```

**Comment by jackhall** [comment]
That's more complicated, which is definitely a sacrifice. Only the first call is actually stepping across an event boundary. Is there some reason you can't call `step_across` once and then simply set the state and call `reset` in lieu of the second call?
